In [1]:
def greet_john_function():
    print("Hello John")
    print("How are you?")
greet_john_function()

Hello John
How are you?


In [2]:
def multiply(a,b,c):
    return a*b*c
multiply(2,4,5)

40

In [3]:
def function_a():
    global b
    a=2
    b=3
    return a + b
def function_b():
    c=5
    return b+c
function_a()
function_b()

8

In [11]:
import numpy as np

a=np.array([[4,5,6],[3,2,5]])

In [12]:
a

array([[4, 5, 6],
       [3, 2, 5]])

In [13]:
type(a)

numpy.ndarray

In [17]:
a.shape

(2, 3)

In [19]:
array1=np.array([[3,5,6,8,9],[6,7,5,4,5],[9,7,6,4,3]])
print(array1)


[[3 5 6 8 9]
 [6 7 5 4 5]
 [9 7 6 4 3]]


In [20]:
np.random.random((4,5))

array([[0.40579774, 0.47312229, 0.66218636, 0.37624522, 0.8990572 ],
       [0.23767088, 0.24431266, 0.97688541, 0.23024925, 0.40820939],
       [0.3824927 , 0.52916747, 0.14935115, 0.79791718, 0.54006273],
       [0.54601522, 0.7290512 , 0.61436606, 0.64932089, 0.4637348 ]])

In [21]:
## Creating a sequence of integers from 14 49 with steps of 7
array4=np.arange(14,49,7)
print(array4)

[14 21 28 35 42]


In [29]:
array1.sum(axis = 0)

array([18, 19, 17, 16, 17])

In [30]:
np.sqrt(array1)

array([[1.73205081, 2.23606798, 2.44948974, 2.82842712, 3.        ],
       [2.44948974, 2.64575131, 2.23606798, 2.        , 2.23606798],
       [3.        , 2.64575131, 2.44948974, 2.        , 1.73205081]])

In [31]:
np.sin(array1)

array([[ 0.14112001, -0.95892427, -0.2794155 ,  0.98935825,  0.41211849],
       [-0.2794155 ,  0.6569866 , -0.95892427, -0.7568025 , -0.95892427],
       [ 0.41211849,  0.6569866 , -0.2794155 , -0.7568025 ,  0.14112001]])

In [35]:
np.sort(array1, axis = 0)

array([[3, 5, 5, 4, 3],
       [6, 7, 6, 4, 5],
       [9, 7, 6, 8, 9]])

In [36]:
np.sort(array1, axis = 1)

array([[3, 5, 6, 8, 9],
       [4, 5, 5, 6, 7],
       [3, 4, 6, 7, 9]])

In [38]:
##Slicing elements from 3rd row
print(array1[0,...])

[3 5 6 8 9]


In [39]:
array1[0,...]

array([3, 5, 6, 8, 9])

## LESSON 6 HOMEWORK

In [5]:
# HW Exercise 1: Write a Python function which will sum all the following 
# listed items (5,8,2,4,7,9)

In [9]:
def sum_all(a, b, c, d, e, f):
    return a+b+c+d+e+f
sum_all(5,8,2,4,7,9)

35

In [10]:
# HW Exercise 2: Write a Python function which will find the product/multiply
# the items in the following list: (4,3,5,6,2)¶
def function():
    a= 4
    b= 3
    c= 5
    d= 6
    e= 2
    return a*b*c*d*e
function()

720

In [40]:
# HW Exercise: Given the following array:
array_hw=np.array([[5,5,8,8,9,8],[7,7,5,3,5,7],[8,7,8,4,2,6],[9,9,7,3,1,4]])
print(array_hw)

[[5 5 8 8 9 8]
 [7 7 5 3 5 7]
 [8 7 8 4 2 6]
 [9 9 7 3 1 4]]


In [46]:
# Using numpy:
# a. sort the flattened array
flat_array_hw = array_hw.flatten()
print(np.sort(flat_array_hw))

[1 2 3 3 4 4 5 5 5 5 6 7 7 7 7 7 8 8 8 8 8 9 9 9]


In [48]:
# b. sort the second column
print(np.sort(array_hw[...,1]))

[5 7 7 9]


In [52]:
# c. sort the third row
print(np.sort(array_hw[2,...]))

[2 4 6 7 8 8]


In [53]:
# d. extract the second row onwards
print(np.sort(array_hw[1:,...]))

[[3 5 5 7 7 7]
 [2 4 6 7 8 8]
 [1 3 4 7 9 9]]


In [54]:
# e. extract the third column onwards
print(np.sort(array_hw[...,2:]))

[[8 8 8 9]
 [3 5 5 7]
 [2 4 6 8]
 [1 3 4 7]]


In [56]:
# f.obtain the square of array_hw
print(np.square(array_hw))

[[25 25 64 64 81 64]
 [49 49 25  9 25 49]
 [64 49 64 16  4 36]
 [81 81 49  9  1 16]]


In [57]:
# g.Slice the element from the third row and fourth column position 3X4
print(array_hw[2,3])

4


In [58]:
# f. obtain the total sum of array_hw
print(np.sum(array_hw))

145


In [59]:
# h. how many dimentions does array_hw have?
array_hw.ndim

2

In [62]:
# i. what is the data type listed in array_hw
array_hw.dtype

dtype('int64')

In [64]:
# j. What is the size of the memory in bytes consumed by all the elements in array_hw
array_hw.nbytes

192